# import = [
#     "~/.config/alacritty/themes/themes/github_light_high_contrast.toml"
# ]
#
[env]
TERM = "xterm-256color"

[cursor]
blink_interval = 300
blink_timeout = 0

[cursor.style]
blinking = "Always"
shape = "Block"

[window]
decorations = 'Buttonless'
dynamic_padding = false
opacity = 1.00
dynamic_title = true

[window.padding]
x = 4
y = 4

[font]
size = 15
normal = {family="JetBrainsMono Nerd Font", style="Regular"}

[keyboard]
bindings = [
  { key = "Right", mods = "Alt", chars = "\u001BF" },
  { key = "Left",  mods = "Alt", chars = "\u001BB" },
]

