 [colors.primary]
 background = '#080808'
 foreground = '#fefefe'
 
 [colors.cursor]
 text = '#181818'
 cursor = '#d8d8d8'
 
 # Normal colors
 [colors.normal]
 black   = '#181818'
 red     = '#ab4642'
 green   = '#a1b56c'
 yellow  = '#f7ca88'
 blue    = '#7cafc2'
 magenta = '#ba8baf'
 cyan    = '#86c1b9'
 white   = '#d8d8d8'
 
 # Bright colors
 [colors.bright]
 black   = '#585858'
 red     = '#ab4642'
 green   = '#a1b56c'
 yellow  = '#f7ca88'
 blue    = '#7cafc2'
 magenta = '#ba8baf'
 cyan    = '#86c1b9'
 white   = '#f8f8f8'

[env]
TERM = "xterm-256color"

[cursor]
blink_interval = 300
blink_timeout = 0

[cursor.style]
blinking = "Always"
shape = "Block"

[window]
decorations = "Buttonless"
dynamic_padding = false
opacity = 1.0
startup_mode = "Windowed"
dynamic_title = true

[window.padding]
x = 8
y = 8

[font]
size = 15
normal = {family="Cascadia Mono", style="Regular"}

[keyboard]
bindings = [
  { key = "Right", mods = "Alt", chars = "\u001BF" },
  { key = "Left",  mods = "Alt", chars = "\u001BB" },
]
